### ISSUE TITLE
Saving checkpoint raises error

### ISSUE THREAD

**Issue by dhanajitb** [soochan-lee/CN-DPM#5]
When I change the ckpt_step from 1000000000 to 10000 in cifar10-cndpm.yaml, it ave the following error:
```
Saving checkpoint... Traceback (most recent call last):
  File "main.py", line 92, in <module>
    main()
  File "main.py", line 88, in main
    train_model(config, model, data_scheduler, writer)
  File "./CN-DPM/train.py", line 76, in train_model
    pickle.dump(model, f)
AttributeError: Can't pickle local object 'CnnSharingVae.__init__.<locals>.<lambda>'
```

**Comment by soochan-lee** [comment]
The checkpoint functionality is not working. For now, I removed the codes related to checkpoint saving to prevent confusion.

To save checkpoints, you would need to write quite some code because `Ndpm` is not a simple `nn.Module`. It has short-term memory and a variable number of experts. Actually, that's one of the reasons we put off implementing the functionality.
